# Generated by Django 4.0.5 on 2022-06-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichapersonaje', '0003_remove_caracteristicas_caracteristica_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracteristicas',
            new_name='Caracteristica',
        ),
        migrations.CreateModel(
            name='Secundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_secundaria', models.CharField(max_length=200)),
                ('coste', models.IntegerField(default=2)),
                ('valor', models.IntegerField(default=-30)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichapersonaje.caracteristica')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichapersonaje.personaje')),
            ],
        ),
    ]
