# Generated by Django 4.0.5 on 2022-06-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichapersonaje', '0006_alter_caracteristica_valor_alter_secundaria_coste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secundaria',
            name='campo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
