# Generated by Django 4.0.6 on 2022-07-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichapersonaje', '0009_alter_caracteristica_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secundaria',
            name='caracteristica',
        ),
        migrations.RemoveField(
            model_name='secundaria',
            name='personaje',
        ),
        migrations.DeleteModel(
            name='Caracteristica',
        ),
        migrations.DeleteModel(
            name='Secundaria',
        ),
    ]
