# Generated by Django 4.0.5 on 2022-06-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichapersonaje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristicas',
            old_name='nombre_característica',
            new_name='nombre_caracteristica',
        ),
    ]
