# Generated by Django 4.0.5 on 2022-06-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichapersonaje', '0005_alter_caracteristica_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='valor',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='secundaria',
            name='coste',
            field=models.CharField(default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='secundaria',
            name='valor',
            field=models.CharField(default=-30, max_length=3),
        ),
    ]
